# Generated by Django 4.2.7 on 2026-02-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidtrace', '0002_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beneficiaries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
